//! Anthropic Files API client.
//!
//! Handles upload/download/delete of files for use in Messages API
//! (file_id references instead of base64) and code_execution sandbox.

const API_BASE: &str = "https://api.anthropic.com/v1/files";
const BETA_HEADER: &str = "files-api-2025-04-14";

fn headers(api_key: &str) -> reqwest::header::HeaderMap {
    let mut h = reqwest::header::HeaderMap::new();
    h.insert("x-api-key", api_key.parse().unwrap());
    h.insert("anthropic-version", "2023-06-01".parse().unwrap());
    h.insert("anthropic-beta", BETA_HEADER.parse().unwrap());
    h
}

/// Upload a file to Anthropic Files API. Returns the file_id.
pub async fn upload_file(
    api_key: &str,
    filename: &str,
    bytes: &[u8],
    mime_type: &str,
) -> Result<String, String> {
    let client = reqwest::Client::new();

    let part = reqwest::multipart::Part::bytes(bytes.to_vec())
        .file_name(filename.to_string())
        .mime_str(mime_type)
        .map_err(|e| format!("invalid mime type: {e}"))?;

    let form = reqwest::multipart::Form::new().part("file", part);

    let resp = client
        .post(API_BASE)
        .headers(headers(api_key))
        .multipart(form)
        .send()
        .await
        .map_err(|e| format!("upload failed: {e}"))?;

    if !resp.status().is_success() {
        let status = resp.status();
        let body = resp.text().await.unwrap_or_default();
        return Err(format!("upload returned {status}: {body}"));
    }

    let body: serde_json::Value = resp.json().await
        .map_err(|e| format!("parse error: {e}"))?;

    body["id"].as_str()
        .map(|s| s.to_string())
        .ok_or_else(|| "no file id in response".to_string())
}

/// Download a file generated by code_execution/skills. Returns (filename, bytes).
/// Note: only files created by code_execution are downloadable, not user-uploaded files.
pub async fn download_file(api_key: &str, file_id: &str) -> Result<(String, Vec<u8>), String> {
    let client = reqwest::Client::new();

    // Get metadata for filename
    let meta_resp = client
        .get(format!("{API_BASE}/{file_id}"))
        .headers(headers(api_key))
        .send()
        .await
        .map_err(|e| format!("metadata request failed: {e}"))?;

    let filename = if meta_resp.status().is_success() {
        let meta: serde_json::Value = meta_resp.json().await.unwrap_or_default();
        meta["filename"].as_str().unwrap_or("output").to_string()
    } else {
        "output".to_string()
    };

    // Download content
    let resp = client
        .get(format!("{API_BASE}/{file_id}/content"))
        .headers(headers(api_key))
        .send()
        .await
        .map_err(|e| format!("download failed: {e}"))?;

    if !resp.status().is_success() {
        return Err(format!("download returned {}", resp.status()));
    }

    let bytes = resp.bytes().await.map_err(|e| format!("read failed: {e}"))?;
    Ok((filename, bytes.to_vec()))
}

/// Delete a file from Anthropic. Best-effort — failures are logged, not fatal.
pub async fn delete_file(api_key: &str, file_id: &str) -> Result<(), String> {
    let client = reqwest::Client::new();

    let resp = client
        .delete(format!("{API_BASE}/{file_id}"))
        .headers(headers(api_key))
        .send()
        .await
        .map_err(|e| format!("delete failed: {e}"))?;

    if !resp.status().is_success() {
        let status = resp.status();
        let body = resp.text().await.unwrap_or_default();
        return Err(format!("delete returned {status}: {body}"));
    }

    Ok(())
}
